//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class hall
    {
        [Required]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "hall name must be between 1-50 letters")]
        public string name { get; set; }
        [Required]
        public int seatsNumber { get; set; }
    }
}
