//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinemaDB : DbContext
    {
        public cinemaDB()
            : base("name=cinemaDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<hall> halls { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<tikit> tikits { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<cartView> cartViews { get; set; }
        public virtual DbSet<moviegallary> moviegallaries { get; set; }
        public virtual DbSet<ticketView> ticketViews { get; set; }
    }
}
