//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class movie
    {
        [Key]
        [Required]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "movie name must be between 4-50 letters")]
        public string name { get; set; }

        [Required]
        public string discription { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "category name must be between 1-50 letters")]

        public string category { get; set; }
        [Required]
        public int agelimit { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string image { get; set; }
        [Required]
        public HttpPostedFileBase ImageFile { get; set; }

    }
}
