//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketView
    {
        public string username { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string discription { get; set; }
        public string category { get; set; }
        public Nullable<decimal> rating { get; set; }
        public int agelimit { get; set; }
        public System.DateTime starttime { get; set; }
        public string hall { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> sale { get; set; }
        public int seat { get; set; }
        public System.DateTime endtime { get; set; }
    }
}
