//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tikit
    {
        public string username { get; set; }
        public string name { get; set; }
        [Required]
        public string hall { get; set; }
        [Required]
        public System.DateTime starttime { get; set; }
        [Required]
        public System.DateTime endtime { get; set; }
        public int seat { get; set; }
        [Required]
        public decimal price { get; set; }
        public Nullable<decimal> sale { get; set; }
    }
}
